Class {
	#name : #DataFrameChartDescription,
	#superclass : #DataChartDescription,
	#instVars : [
		'dataFrame'
	],
	#category : #'Data-Chart-Description'
}

{ #category : #accessing }
DataFrameChartDescription >> dataFrame: aCollection [ 
	dataFrame := aCollection
]

{ #category : #accessing }
DataFrameChartDescription >> x: aString [ 
	
]

{ #category : #accessing }
DataFrameChartDescription >> y: aString [ 
	
]
